### ISSUE TITLE
Quick question on contributing to the project

### ISSUE THREAD

**Issue by Eimaen** [MDModsDev/MiscToolsForMD#2]
Hi 👋! I've noticed that you are implementing synced lyrics for Muse Dash. I want to add Musixmatch lyrics source. Is it ok to ship additional dependency that provides Musixmatch API for lyrics?

**Comment by zhanghua000** [comment]
It depends you, it will be better if you implement it without any extra dependency. You can always go ahead if you think the dependence is needed without doubt.
Please also note that the APIs of synced lyric are not stable, they are just a draft, we are working on fixing accuracy calculation bugs now.

**Comment by Eimaen** [comment]
Thanks for your response. One more question: is there any other way to contact the maintainers of this repo to discuss further changes?

**Comment by zhanghua000** [comment]
Most of us are active on [Discord](https://discord.gg/mdmc) mainly, please feel free to join us. However, this repo are not developed actively because I have some more important things to do recently like finding a job.

**Comment by Eimaen** [comment]
Thanks, closing the issue.
